app:
  port: ":8080"
  ttl_default: "720h"
  cleanup_period: "24h"

storage:
  sqlite:
    database: ""

  postgresql:
    host: "localhost"       
    port: "5432"              
    user: "user"          
    password: "password"  
    dbname: "db"          
    sslmode: "disable"      